# Generated by Django 2.2.1 on 2019-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds2api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='dds2api.Role'),
        ),
    ]
